// Generated by CoffeeScript 1.6.3
(function() {
  var $ele, current_url, pages, watcher, watcher_loop;

  $('html').addClass('pudu');

  current_url = "" + window.location.href;

  pages = {
    thread: current_url.indexOf('.com/thread/') !== -1
  };

  $ele = {
    controlBar: $('.posts > .control-bar'),
    postHeader: $('.posts .content-head')
  };

  watcher = {};

  watcher_loop = function() {
    var func, name;
    for (name in watcher) {
      func = watcher[name];
      func();
    }
    return setTimeout(watcher_loop, 1000);
  };

  watcher_loop();

  if (pages.thread) {
    watcher['add_thread_pagination'] = function() {
      var $ctb, ctbHtml, page;
      page = $ele.controlBar.find('.state-selected').text();
      if ($ele.controlBar.data('page') !== page) {
        $ctb = $ele.controlBar.clone();
        $ctb.find('> div').remove();
        ctbHtml = '<div class="control-bar ui-helper-clearfix pudu-thread-pagination" style="text-align: center"><div>' + $ctb.html() + '</div></div>';
        $('.pudu-thread-pagination').remove();
        $('.posts > .content').after(ctbHtml);
        return $ele.controlBar.data('page', page);
      }
    };
    watcher['add_focus_to_comment'] = function() {
      return $('.posts .content-head').each(function() {
        var focus, score;
        if (!$(this).data('done')) {
          if ($('.likes a', this).size() > 0) {
            if ($('.view-likes', this).size() === 0) {
              focus = 1;
            } else {
              score = 2 + parseInt($('.view-likes', this).text().replace([' more', ','], ''));
              if (score < 10) {
                focus = 2;
              } else if (score < 20) {
                focus = 3;
              } else if (score < 30) {
                focus = 4;
              } else if (score < 40) {
                focus = 5;
              }
            }
            $(this).parents('article').addClass('focus-' + focus);
            $(this).parent().find('.message').css({
              'margin': 0,
              'minHeight': 350
            });
          }
          return $(this).data('done', true);
        }
      });
    };
  }

}).call(this);

/*
//@ sourceMappingURL=default.map
*/
