// Generated by CoffeeScript 1.6.3
(function() {
  var $elements, current_url, pages;

  $('html').addClass('pudu');

  current_url = "" + window.location.href;

  pages = {
    thread: current_url.indexOf('.com/thread/') !== -1,
    board: current_url.indexOf('.com/board/') !== -1
  };

  $elements = {
    controlBar: $('.posts > .control-bar'),
    postHeader: $('.posts .content-head'),
    threads: $('.threads .thread')
  };

  pudu.watcherLoop();

  if (pages.board) {
    pudu.watcher['thread_title_link_to_front_page'] = function() {
      return pudu.watcherElementIterator($elements.threads, function($ele) {
        var $l;
        $l = $ele.find('.link.target > a');
        return $l.attr('href', $l.attr('href').replace('s/recent/', '/') + '?page=1');
      });
    };
  }

  if (pages.thread) {
    pudu.watcher['add_thread_pagination'] = function() {
      var $ctb, ctbHtml, page;
      page = $elements.controlBar.find('.state-selected').text();
      if ($elements.controlBar.data('page') !== page) {
        $ctb = $elements.controlBar.clone();
        $ctb.find('> div').remove();
        ctbHtml = '<div class="control-bar ui-helper-clearfix pudu-thread-pagination" style="text-align: center"><div>' + $ctb.html() + '</div></div>';
        $('.pudu-thread-pagination').remove();
        $('.posts > .content').after(ctbHtml);
        return $elements.controlBar.data('page', page);
      }
    };
    pudu.watcher['add_focus_to_comment'] = function() {
      return pudu.watcherElementIterator($('.posts .content-head'), function($ele, that) {
        var focus, score;
        if ($('.likes a', that).size() > 0) {
          if ($('.view-likes', that).size() === 0) {
            focus = 1;
          } else {
            score = 2 + parseInt($('.view-likes', that).text().replace([' more', ','], ''));
            if (score < 10) {
              focus = 2;
            } else if (score < 20) {
              focus = 3;
            } else if (score < 30) {
              focus = 4;
            } else if (score < 40) {
              focus = 5;
            }
          }
          $(that).parents('article').addClass('focus-' + focus);
          return $(that).parent().find('.message').css({
            'margin': 0,
            'minHeight': 285
          });
        }
      });
    };
  }

}).call(this);

/*
//@ sourceMappingURL=default.map
*/
